# Generated by Django 3.2.4 on 2021-06-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createEvent', '0002_auto_20210610_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
    ]
