# Generated by Django 3.2.4 on 2021-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvent', '0003_rename_title_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
