# Generated by Django 3.2.4 on 2021-06-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createEvent', '0005_auto_20210613_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='mail',
            new_name='email',
        ),
    ]
