# Generated by Django 3.2.4 on 2021-06-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvent', '0007_auto_20210615_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
