# Generated by Django 3.2.4 on 2021-06-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvent', '0009_auto_20210618_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
