# Generated by Django 3.2.3 on 2021-06-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
